version: '3.9'

services:

  web:
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - ./beneficios:/var/www/html
      - ./docker-server.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: bitnami/php-fpm:latest
    volumes:
      - ./beneficios:/var/www/html
  mysql:
    image: mariadb:latest
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - 3306:3306